### ISSUE TITLE
turn on captions with `track` element

### ISSUE THREAD

**Issue by imahdio** [imahdio/HTML-Essential-Training#6]
I'm studying [Captions and subtitles lesson](http://168.119.85.43/html-essential-training-4/07-Media/03-Captions%20and%20subtitles.mp4) from  HTML Essential Training  course.

the prblem is , why the subtitle feature of the following code snippet not working?
```html
<video controls>
  <source src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/10558/moonwalk.480p.vp9.webm" 
    type="video/webm">
  <source src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/10558/moonwalk.480p.h264.mp4" 
    type="video/mp4">
  
  <track src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/10558/moonwalk.vtt"
         kind="captions"
         label="English"
         srclang="en"
         default>
  
   <track src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/10558/moonwalk.es-la.es.vtt"
         kind="subtitles"
         label="Español"
         srclang="es">
  
  <p>This would be a video of a moonwalk, if your device supported playing this video.</p>
</video>
```

[check the original code in interactive environment of codepen.io](https://codepen.io/jensimmons/pen/KKPevBe?editors=1000)

### **try to troubleshoot it to trigger the caption feature and report the results**

NTOICE: [this website](https://www.happyscribe.com) give direct link access to any uploaded .vtt subtitle to experiment on HTML codes like the following image:
![image](https://user-images.githubusercontent.com/64577273/146765488-a3d960b6-e8de-4a87-82c3-b62df1befb78.png)

**Comment by ghost** [comment]
maybe because the browser doesn't support it... its weird indeed... I will try later...

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/34148935/146768540-a2fe75f4-51f7-479f-acba-5a82892e10ad.png)

just check the console... it has error because the domain is not allowed

**Comment by MBEDOBE** [comment]
the code here looks fine to me, it shows the labels correctly . do you have access to the subtitle file? i suspect it has something to do with the configurations.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/34148935/146768925-6da3930a-9bcd-4be3-abbd-e8bb646b307c.png)

yeah, maybe it will be solved when you code in your local... its just codepen doesnt allow your code to access another domain

**Comment by ghost** [comment]
try this https://stackoverflow.com/questions/55645393/issue-with-loading-vtt-from-cross-domain

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/34148935/146769357-e965993c-cdb3-4f5c-8edf-bfafa43667c7.png)

add crossorigin="*"

**Comment by MBEDOBE** [comment]
> ![image](https://user-images.githubusercontent.com/34148935/146769357-e965993c-cdb3-4f5c-8edf-bfafa43667c7.png)
> 
> add crossorigin="*"

right, so you add crossorigin attribute to the video element. i used `crossorigin="anonymous"` and its working.

**Comment by imahdio** [comment]
tnx to @MBEDOBE 
it works like charms
code environment:
[https://codepen.io/ma400/pen/rNGwRNr?editors=1100](https://codepen.io/ma400/pen/rNGwRNr?editors=1100)

temporary debug mode:
[https://codepen.io/ma400/debug/rNGwRNr](https://codepen.io/ma400/debug/rNGwRNr)

**Comment by MBEDOBE** [comment]
![captions](https://user-images.githubusercontent.com/25242976/146770548-7ca77ae3-9591-4af2-9c73-a74d6a7ea81e.PNG)

you can also use `crossorigin="*"`  as @nurulaisyah61 suggested in the video tag and it will work fine

**Comment by imahdio** [comment]
![image](https://user-images.githubusercontent.com/64577273/146773211-89fb9838-c071-44dd-97a3-918e3f9bee62.png)
why do the browser give unsafe attempt error even when try to excete that code on local host by index.html ??
with this assumption I donot use crossorigin="*"

> ![image](https://user-images.githubusercontent.com/34148935/146768925-6da3930a-9bcd-4be3-abbd-e8bb646b307c.png)
> 
> yeah, maybe it will be solved when you code in your local... its just codepen doesnt allow your code to access another domain

**Comment by MBEDOBE** [comment]
> ![image](https://user-images.githubusercontent.com/64577273/146773211-89fb9838-c071-44dd-97a3-918e3f9bee62.png) why do the browser give unsafe attempt error even when try to excete that code on local host by index.html ?? with this assumption I donot use crossorigin="*"
> 
> > ![image](https://user-images.githubusercontent.com/34148935/146768925-6da3930a-9bcd-4be3-abbd-e8bb646b307c.png)
> > yeah, maybe it will be solved when you code in your local... its just codepen doesnt allow your code to access another domain

i think they have to be on the same path, because the video and subtitles are hosted on the aws platform whereas you're trying to execute from localhost.

**Comment by imahdio** [comment]
![image](https://user-images.githubusercontent.com/64577273/146777096-9fc197b8-d37e-4dff-8371-e8ad5de01dcd.png)

even with same files source
with same unsafe attempt error

> > ![image](https://user-images.githubusercontent.com/64577273/146773211-89fb9838-c071-44dd-97a3-918e3f9bee62.png) why do the browser give unsafe attempt error even when try to excete that code on local host by index.html ?? with this assumption I donot use crossorigin="*"
> > > ![image](https://user-images.githubusercontent.com/34148935/146768925-6da3930a-9bcd-4be3-abbd-e8bb646b307c.png)
> > > yeah, maybe it will be solved when you code in your local... its just codepen doesnt allow your code to access another domain
> 
> i think they have to be on the same path, because the video and subtitles are hosted on the aws platform whereas you're trying to execute from localhost.

**Comment by ghost** [comment]
> i think they have to be on the same path, because the video and subtitles are hosted on the aws platform whereas you're trying to execute from localhost.

yeah, I think you right, I just realized it too... thank you

**Comment by ghost** [comment]
> even with same files source
> with same unsafe attempt error

https://stackoverflow.com/a/61729375

how about this?

**Comment by MBEDOBE** [comment]
> > even with same files source
> > with same unsafe attempt error
> 
> https://stackoverflow.com/a/61729375
> 
> how about this?

i'll test it and get back on this

**Comment by ghost** [comment]
hmm I think the most right and easy answer is still `crossorigin="anonymous"` haha

https://textslashplain.com/2019/10/09/navigating-to-file-urls/

**Comment by MBEDOBE** [comment]
> > > even with same files source
> > > with same unsafe attempt error
> > 
> > 
> > https://stackoverflow.com/a/61729375
> > how about this?
> 
> i'll test it and get back on this

![test2 1](https://user-images.githubusercontent.com/25242976/146781269-eed61ab6-6b4b-4a9e-8515-6cf205486c94.PNG)

![test2 2](https://user-images.githubusercontent.com/25242976/146781283-603fba49-a6dc-4e9a-9f19-aa98da7a4b5f.PNG)

@nurulaisyah61 @imahdio 
so i tested it in my IDE and if all files are in the same directory on localhost, it will work correctly as shown in the images above. in the first image i have my video file and subtitle file in same folder.  so without adding the crossorigin attribute, it works as shown in image 2

**Comment by imahdio** [comment]
as you could see in following code snippet
https://codepen.io/jensimmons/pres/KKPevBe?editors=1100

opposite of our expectation , the available subtitles of that video player doesn't appear.

one study friend (@nurulaisyah61) found the solution by adding the following attribute inside `<video>` tag.
crossorigin="*"

here is the fixed version of that player:
https://codepen.io/ma400/pen/rNGwRNr

**the question is , what caused the problem and why that attribute fix the problem??**

**Comment by sharmag44** [comment]
with corrsorigin="*" it solved and after it doesn't work then create local file  to findout  error[ https://replit.com/@sharmag44/videocaption#index.html](url)
