### ISSUE TITLE
define meaning of some complicated vocabulary

### ISSUE THREAD

**Issue by imahdio** [imahdio/HTML-Essential-Training#7]
based [THIS VIDEO](https://cdpn.io/ma400/debug/rNGwRNr/PNrvYXewGPvM)
what's the meaning of 

1. leave that one foot up there

2. about the fourth rung up

3. about another inch

4. three-footer

plz define meaning of each one of above phrase one by one based the context.
plz leave your replies based english to english dictionaries

**Comment by MRGHOSJ** [comment]
1. leave that one foot up there (at 0:03)
The astronaut was simply referring to his foot to leave it flowting in the air (space)
2. about the fourth rung up (at 0:007)
A rung is a step in the ladder (Rungs serve the same function as steps on a step ladder. The only difference between rungs on an extension ladder and step ladder is that rungs on an extension ladder are half as deep to allow the fly section to slide up and down.)
fourth rung up just means fourth step up the ladder
3. about another inch (at 0:23)
inch is a unit of length in the British imperial and the United States customary systems of measurement.
about another inch just means a little bit more
4. three-footer (at 0:30)
The foot, standard symbol: ft, is a unit of length in the British imperial and United States customary systems of measurement.
three-footer => 0.9144 meters 
i guess he was referring to how long was the jump or so

**Comment by imahdio** [comment]
Hi dear @MRGHOSJ 
Very tnx for your very great and descriptive definition
